logger:
  level: 0
server:
  route: /anomaly
  port: 3333
algorithm:
  temperature:
    lambda: 0.25
    lFactor: 3
    controlT: 90
    controlS: 20
    controlN: 10
  vibration:
    lambda: 0.25
    lFactor: 3
    controlT: 50
    controlS: 20
    controlN: 10
  humidity:
    lambda: 0.25
    lFactor: 3
    controlT: 80
    controlS: 20
    controlN: 10
