logger:
  level: 0
servers:
  http:
    port: 3333
    resources:
      - path: /example
        method: GET
        status: 200
        outputs: ["output1", "output2"]
        response: |
          {
            "hello": "world"
          }
      - path: /example
        method: POST
        status: 200
        outputs: ["output3", "output4"]
        response: |
          {
            "hello": "world1"
          }
  grpc:
    port: 3334
    outputs: ["output1", "output4"]
outputs:
  - name: output1
    type: stdout
  - name: output2
    type: mqtt
    qos: 1
    path: default/output1
    endpoint: localhost:1883
  - name: output3
    type: mqtt
    qos: 1
    path: default/output2
    endpoint: localhost:1883
  - name: output4
    type: mqtt
    qos: 1
    path: grpc/example
    endpoint: localhost:1883
